spring.application.name=job.applicants
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/jobapplicantsdb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# log to file
logging.file.name=logs/app.log

# ===============================
# SWAGGER Configuration
# ===============================
springdoc.swagger-ui.path=/docs

springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true


